In [10]:
import networkx as nx
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.mlab as mlab
from collections import Counter
import pickle
import itertools
import os

Choose the dataset

In [11]:
dataset = 'pr_school'
filename = 'data/primaryschool.csv'

filename is the path to the datsset, like "data/primaryschool.csv"

In [12]:
time_list = []
person1_list = []
person2_list = []
for line in open(filename):
    csv_row = line.split()
    time_list.append(int(csv_row[0]))
    person1_list.append(int(csv_row[1]))
    person2_list.append(int(csv_row[2]))

Reassign nodes identities such that they start from 0 and go up to N:

In [13]:
nodes = np.unique(person1_list+person2_list)
nodes

array([1426, 1427, 1428, 1429, 1430, 1431, 1434, 1435, 1437, 1439, 1441,
       1443, 1451, 1452, 1453, 1457, 1458, 1459, 1461, 1465, 1468, 1471,
       1475, 1477, 1479, 1480, 1482, 1483, 1486, 1489, 1493, 1495, 1498,
       1500, 1501, 1502, 1503, 1504, 1511, 1516, 1519, 1520, 1521, 1522,
       1524, 1525, 1528, 1532, 1533, 1538, 1539, 1545, 1546, 1548, 1549,
       1551, 1552, 1555, 1558, 1560, 1562, 1563, 1564, 1567, 1570, 1572,
       1574, 1578, 1579, 1580, 1585, 1592, 1594, 1601, 1603, 1604, 1606,
       1609, 1613, 1616, 1617, 1618, 1625, 1628, 1630, 1632, 1637, 1641,
       1643, 1647, 1648, 1649, 1650, 1653, 1656, 1661, 1663, 1664, 1665,
       1666, 1668, 1670, 1673, 1674, 1675, 1680, 1681, 1682, 1684, 1685,
       1687, 1688, 1695, 1696, 1697, 1698, 1700, 1702, 1704, 1705, 1706,
       1707, 1708, 1709, 1710, 1711, 1712, 1713, 1714, 1715, 1718, 1719,
       1720, 1722, 1723, 1727, 1730, 1731, 1732, 1735, 1737, 1738, 1739,
       1741, 1743, 1744, 1745, 1746, 1748, 1749, 17

array([1426, 1427, 1428, 1429, 1430, 1431, 1434, 1435, 1437, 1439, 1441,
       1443, 1451, 1452, 1453, 1457, 1458, 1459, 1461, 1465, 1468, 1471,
       1475, 1477, 1479, 1480, 1482, 1483, 1486, 1489, 1493, 1495, 1498,
       1500, 1501, 1502, 1503, 1504, 1511, 1516, 1519, 1520, 1521, 1522,
       1524, 1525, 1528, 1532, 1533, 1538, 1539, 1545, 1546, 1548, 1549,
       1551, 1552, 1555, 1558, 1560, 1562, 1563, 1564, 1567, 1570, 1572,
       1574, 1578, 1579, 1580, 1585, 1592, 1594, 1601, 1603, 1604, 1606,
       1609, 1613, 1616, 1617, 1618, 1625, 1628, 1630, 1632, 1637, 1641,
       1643, 1647, 1648, 1649, 1650, 1653, 1656, 1661, 1663, 1664, 1665,
       1666, 1668, 1670, 1673, 1674, 1675, 1680, 1681, 1682, 1684, 1685,
       1687, 1688, 1695, 1696, 1697, 1698, 1700, 1702, 1704, 1705, 1706,
       1707, 1708, 1709, 1710, 1711, 1712, 1713, 1714, 1715, 1718, 1719,
       1720, 1722, 1723, 1727, 1730, 1731, 1732, 1735, 1737, 1738, 1739,
       1741, 1743, 1744, 1745, 1746, 1748, 1749, 17

In [14]:
new_nodes = np.arange(len(nodes))
new_nodes

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [15]:
conversion = {}
for i in range(len(nodes)):
    conversion[nodes[i]] = new_nodes[i]

In [16]:
new_person1_list = []
for node in person1_list:
    new_person1_list.append(conversion[node])
    
new_person2_list = []
for node in person2_list:
    new_person2_list.append(conversion[node])

Find interactions at every time:

In [17]:
def interaction_network_at_given_time(instant):
    edge_list = []
    for t in range(len(time_list)):
        if time_list[t] == instant:
            edge_list.append([new_person1_list[t],new_person2_list[t]])
    G=nx.Graph()
    G.add_edges_from(edge_list)
    return G

In [18]:
Dpairwise = {}
D2 = {}
D3 = {}
D4 = {}
D5 = {}

time = 0
while time < max(time_list):
    G0 = interaction_network_at_given_time(time)
    cliques = list(nx.find_cliques(G0))

    for clique in cliques:
        clique = list(np.sort(clique))
        size = len(clique)
        if size == 2:
            if tuple(clique) in D2:
                D2[tuple(clique)] += 1
            else:
                D2[tuple(clique)] = 1
        elif size == 3:
            if tuple(clique) in D3:
                D3[tuple(clique)] += 1
            else:
                D3[tuple(clique)] = 1
        elif size == 4:
            if tuple(clique) in D4:
                D4[tuple(clique)] += 1
            else:
                D4[tuple(clique)] = 1
        elif size == 5:
            if tuple(clique) in D5:
                D5[tuple(clique)] += 1
            else:
                D5[tuple(clique)] = 1
        elif size > 5:
            print(clique)
            
    pairwise_links = list(G0.edges)
    for edge in pairwise_links:
        edge = list(np.sort(edge))
        if tuple(edge) in Dpairwise:
            Dpairwise[tuple(edge)] += 1
        else:
            Dpairwise[tuple(edge)] = 1
            
    time += 20

Normalize pairwise:

In [19]:
Dpairwise_n = {}
for key in Dpairwise:
    Dpairwise_n[key] = Dpairwise[key]/max(Dpairwise.values())

Save all pairwise:

In [20]:
folder = 'data/pairwise/'
if not os.path.exists(folder):
    os.makedirs(folder)
dict_name = folder + '%s_strength_edgelist_pairwise_sorted_norm.pkl'%dataset
with open(dict_name, 'wb') as f:
    pickle.dump(Dpairwise_n, f)

I build another dictionary which includes all higher orders interactions as triangles:

In [21]:
D3ho = D3.copy()

In [22]:
for clique in D4.keys():
    for triplet in itertools.combinations(clique,3): #all possible triplets in clique
        triplet = list(np.sort(triplet))
        if tuple(triplet) in D3ho:
            D3ho[tuple(triplet)] += 1
        else:
            D3ho[tuple(triplet)] = 1

for clique in D5.keys():
    for triplet in itertools.combinations(clique,3): #all possible triplets in clique
        triplet = list(np.sort(triplet))
        if tuple(triplet) in D3ho:
            D3ho[tuple(triplet)] += 1
        else:
            D3ho[tuple(triplet)] = 1


Normalize second order:

In [23]:
D3ho_n = {}
for key in D3ho:
    D3ho_n[key] = D3ho[key]/max(Dpairwise.values())

Save second order:

In [24]:
folder = 'data/only_triangles/'
if not os.path.exists(folder):
    os.makedirs(folder)

dict_name = folder + '%s_strength_edgelist3_sorted_norm.pkl'%dataset
with open(dict_name, 'wb') as f:
    pickle.dump(D3ho_n, f)